package generator_test

import (
	"testing"

	openapi "github.com/nasa9084/go-openapi"
	"github.com/nasa9084/restgen/internal/generator"
)

func TestGenerateRoutes(t *testing.T) {
	spec := `---
paths:
  /:
    get:
      description: foo
      operationId: Foo
      responses:
        '200':
          $ref: "#/components/responses/FooResponse"
`
	doc, err := openapi.Load([]byte(spec))
	if err != nil {
		t.Fatal(err)
	}
	src, err := generator.GenerateRoutes(doc)
	if err != nil {
		t.Error(err)
		return
	}
	expected := `package main

import (
	"net/http"

	"github.com/gorilla/mux"
)

// code generated by genserver. DO NOT EDIT.

func NewRouter() http.Handler {
	r := mux.NewRouter()
	r.HandleFunc("/", FooHandler).Methods("GET")
	return r
}
`
	if string(src) != expected {
		t.Errorf("%s != %s", string(src), expected)
		return
	}
}
